# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/quote.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="proto/quote.proto",
    package="hipstershop",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x11proto/quote.proto\x12\x0bhipstershop"\x0e\n\x0cQuoteRequest"\x1d\n\nQuoteReply\x12\x0f\n\x07message\x18\x01 \x01(\t2V\n\x0cQuoteService\x12\x46\n\x10GetQuoteOfTheDay\x12\x19.hipstershop.QuoteRequest\x1a\x17.hipstershop.QuoteReplyb\x06proto3',
)


_QUOTEREQUEST = _descriptor.Descriptor(
    name="QuoteRequest",
    full_name="hipstershop.QuoteRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=34,
    serialized_end=48,
)


_QUOTEREPLY = _descriptor.Descriptor(
    name="QuoteReply",
    full_name="hipstershop.QuoteReply",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="message",
            full_name="hipstershop.QuoteReply.message",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=50,
    serialized_end=79,
)

DESCRIPTOR.message_types_by_name["QuoteRequest"] = _QUOTEREQUEST
DESCRIPTOR.message_types_by_name["QuoteReply"] = _QUOTEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QuoteRequest = _reflection.GeneratedProtocolMessageType(
    "QuoteRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _QUOTEREQUEST,
        "__module__": "proto.quote_pb2"
        # @@protoc_insertion_point(class_scope:hipstershop.QuoteRequest)
    },
)
_sym_db.RegisterMessage(QuoteRequest)

QuoteReply = _reflection.GeneratedProtocolMessageType(
    "QuoteReply",
    (_message.Message,),
    {
        "DESCRIPTOR": _QUOTEREPLY,
        "__module__": "proto.quote_pb2"
        # @@protoc_insertion_point(class_scope:hipstershop.QuoteReply)
    },
)
_sym_db.RegisterMessage(QuoteReply)


_QUOTESERVICE = _descriptor.ServiceDescriptor(
    name="QuoteService",
    full_name="hipstershop.QuoteService",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=81,
    serialized_end=167,
    methods=[
        _descriptor.MethodDescriptor(
            name="GetQuoteOfTheDay",
            full_name="hipstershop.QuoteService.GetQuoteOfTheDay",
            index=0,
            containing_service=None,
            input_type=_QUOTEREQUEST,
            output_type=_QUOTEREPLY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_QUOTESERVICE)

DESCRIPTOR.services_by_name["QuoteService"] = _QUOTESERVICE

# @@protoc_insertion_point(module_scope)
